//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcNGDatatable
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePartsItem
    {
        public int Id { get; set; }
        public string PartsNo { get; set; }
        public string PartsName { get; set; }
        public int Quantity { get; set; }
        public string SheetNo { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Amount { get; set; }
        public string Supplier { get; set; }
    }
}
